Bookstore/Controllers/PurchasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Bookstore.Data;
using Bookstore.Models;
using Microsoft.AspNetCore.Authorization;
using TweetSharp;
using System.Linq.Expressions;

namespace Bookstore.Controllers
{
    public class PurchasesController : Controller
    {
        private readonly BookstoreContext _context;
        private readonly BookstoreUserManager _userManager;

        public PurchasesController(BookstoreContext context, 
                                   BookstoreUserManager userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        /*
         * Index            (AUTH GET):          /Purchases/?Params
         * Buy              (AUTH GET+POST):     /Purchases/Buy/?Params
         * Receipt          (AUTH GET):          /Purchases/Receipt/ID
         * BooksStatistics  (AUTH GET):          /Purchases/BooksStatistics
         * GenersStatistics (AUTH GET):          /Purchases/GenersStatistics
         * DatesStatistics  (AUTH GET):          /Purchases/DatesStatistics
         */

        // GET: Purchases
        [Authorize]
        public async Task<IActionResult> Index(string buyerName, string buyerPhone, string bookTitle, string sellerName)
        {
            var purchases = _context.Purchase
                .Join(_context.Customer,        // Get buyer info from customers with purchase's buyer ID
                      purchaseSelector => purchaseSelector.BuyerId,
                      customerSelector => customerSelector.Id,
                (purchase, customer) => new Purchase()
                {
                    // Keep purchase data
                    Id = purchase.Id,
                    PaidPrice = purchase.PaidPrice,
                    OrderDate = purchase.OrderDate,
                    BookId = purchase.BookId,
                    Book = purchase.Book,
                    SellerId = purchase.SellerId,
                    Seller = purchase.Seller,

                    // Get buyer data
                    BuyerId = customer.Id,
                    Buyer = customer
                }).Join(_context.Book,          // Get book info from books with purchase's book ID
                        purchaseSelector => purchaseSelector.BookId,
                        bookSelector => bookSelector.Id,
                (purchase, book) => new Purchase()
                {
                    // Keep purchase data
                    Id = purchase.Id,
                    PaidPrice = purchase.PaidPrice,
                    OrderDate = purchase.OrderDate,
                    BuyerId = purchase.BuyerId,
                    Buyer = purchase.Buyer,
                    SellerId = purchase.SellerId,
                    Seller = purchase.Seller,

                    // Get book data
                    BookId = book.Id,
                    Book = book
                }).Join(_userManager.Users,     // Get seller info from users with purchase's seller ID
                        purchaseSelector => purchaseSelector.SellerId,
                        workerSelector => workerSelector.Id,
                (purchase, worker) => new Purchase()
                {
                    // Keep purchase data
                    Id = purchase.Id,
                    PaidPrice = purchase.PaidPrice,
                    OrderDate = purchase.OrderDate,
                    BuyerId = purchase.BuyerId,
                    Buyer = purchase.Buyer,
                    BookId = purchase.BookId,
                    Book = purchase.Book,

                    // Get book data
                    SellerId = worker.Id,
                    Seller = worker
                }).Select(m => new              // Combine everything with a SELECT clause
                {
                    // Keep purchase data
                    m.Id,
                    m.PaidPrice,
                    m.OrderDate,
                    m.BuyerId,
                    m.Buyer,
                    m.BookId,
                    m.Book,
                    m.SellerId,
                    m.Seller
                }).AsQueryable();

            if (!String.IsNullOrWhiteSpace(buyerName))
                purchases = purchases.Where(x => x.Buyer.Name.Contains(buyerName));
            if (!String.IsNullOrWhiteSpace(buyerPhone))
                purchases = purchases.Where(x => x.Buyer.Phone.Contains(buyerPhone));
            if (!String.IsNullOrWhiteSpace(bookTitle))
                purchases = purchases.Where(x => x.Book.Title.Contains(bookTitle));
            if (!String.IsNullOrWhiteSpace(sellerName))
                purchases = purchases.Where(x => x.Seller.Name.Contains(sellerName));

            var purchasesViewList = new List<PurchaseViewModel>();

            try
            {
                var purchasesList = await purchases.ToListAsync();
            
                foreach (var purchase in purchasesList)
                {
                    var view = new PurchaseViewModel
                    {
                        BuyerName = purchase.Buyer.Name,
                        BuyerPhone = purchase.Buyer.Phone,
                        BookTitle = purchase.Book.Title,
                        PaidPrice = purchase.PaidPrice,
                        SellerName = purchase.Seller.Name,
                        OrderDate = purchase.OrderDate
                    };

                    purchasesViewList.Add(view);
                }
            }
            catch (Exception err)
            {
                throw err;
            }

            return View(purchasesViewList);
        }

        [Authorize]
        private JsonResult Statistics<T>(Expression<Func<Purchase, T>> keySelector)
        {
            var purchases = _context.Purchase
                .Join(_context.Book,          // Get book info from books with purchase's book ID
                        purchaseSelector => purchaseSelector.BookId,
                        bookSelector => bookSelector.Id,
                (purchase, book) => new Purchase()
                {
                    // Keep purchase data
                    Id = purchase.Id,
                    PaidPrice = purchase.PaidPrice,
                    OrderDate = purchase.OrderDate,
                    BuyerId = purchase.BuyerId,
                    Buyer = purchase.Buyer,
                    SellerId = purchase.SellerId,
                    Seller = purchase.Seller,

                    // Get book data
                    BookId = book.Id,
                    Book = book
                }).GroupBy(keySelector).Select(group => new
                {
                    BookId = group.First().BookId,
                    Genre = group.First().Book.Genre,
                    OrderDate = group.First().OrderDate.Date,
                    Count = group.Count(),
                    Revenue = group.Sum(p => p.PaidPrice)
                }).AsQueryable();

            return Json(purchases);
        }

        [Authorize]
        public JsonResult BooksStatistics()
        {
            return Statistics<int>(p => p.BookId);
        }
        [Authorize]
        public JsonResult GenersStatistics()
        {
            return Statistics<String>(p => p.Book.Genre);
        }
        [Authorize]
        public JsonResult DatesStatistics()
        {
            return Statistics<DateTime>(p => p.OrderDate.Date);
        }

        // GET: Purchases/Buy/?Params
        [Authorize]
        public async Task<IActionResult> Buy(String BuyerPhone, int BookId)
        {
            var worker = await _userManager.GetUserAsync(HttpContext.User);
            if (worker == null)
            {
                return RedirectToAction(nameof(WorkersAuthController.AccessDenied), "WorkersAuth");
            }
            if (!string.IsNullOrEmpty(BuyerPhone))
            {
                PurchaseCreationViewModel purchase = new PurchaseCreationViewModel
                {
                    BuyerPhone = BuyerPhone,
                    BookId = BookId
                };
                return View(purchase);
            }
            return View();
        }

        // POST: Purchases/Buy
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Buy([Bind("BuyerPhone,BookId")] PurchaseCreationViewModel purchaseView)
        {
            Worker worker;
            try
            {
                worker = await _userManager.GetUserAsync(HttpContext.User);
            }
            catch
            {
                return RedirectToAction(nameof(WorkersAuthController.AccessDenied), "WorkersAuth");
            }

            if (worker == null)
            {
                return RedirectToAction(nameof(WorkersAuthController.AccessDenied), "WorkersAuth");
            }

            var workerId = worker.Id;

            if (workerId == 0 || String.IsNullOrWhiteSpace(purchaseView.BuyerPhone))
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                // Find corspond related models
                var buyer = await _context.Customer.FirstOrDefaultAsync(b => b.Phone.Equals(purchaseView.BuyerPhone));
                var seller = await _userManager.Users.FirstOrDefaultAsync(b => b.Id == workerId);

Bookstore/Views/Purchases/Buy.cshtml
@model Bookstore.Models.PurchaseCreationViewModel

@{
    ViewData["Title"] = "Buy";
}

<h2>Buy</h2>

<h4>Purchase</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Buy">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BuyerPhone" class="control-label"></label>
                <input asp-for="BuyerPhone" class="form-control" />
                <span asp-validation-for="BuyerPhone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BookId" class="control-label"></label>
                <input asp-for="BookId" class="form-control" />
                <span asp-validation-for="BookId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Buy" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Bookstore/Views/Purchases/Index.cshtml
@model IEnumerable<Bookstore.Models.PurchaseViewModel>

@{
    ViewData["Title"] = "Index";
}

<style>
    #pieChartTitle {
        font-size: 24px;
        margin-left: 100px;
    }

    #postsChart {
        font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
        position: relative;
    }

    path.slice {
        stroke-width: 2px;
    }

    polyline {
        opacity: .3;
        stroke: black;
        stroke-width: 2px;
        fill: none;
    }
</style>

<h2>Index</h2>

<form asp-controller="Purchases" asp-action="Index" method="get">
    <p>
        BuyerName: <input type="text" name="BuyerName">
        BuyerPhone: <input type="text" name="BuyerPhone">
        BookTitle: <input type="text" name="BookTitle">
        SellerName <input type="text" name="SellerName">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.BuyerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BuyerPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BookTitle)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PaidPrice)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SellerName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.OrderDate)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.BuyerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BuyerPhone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BookTitle)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PaidPrice)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SellerName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.OrderDate)
                </td>
            </tr>
        }
    </tbody>
</table>

<svg width="600" height="500"></svg>
<ul id="pieChartTitle">Book's Genres Statistics</ul>
<ul id="postsChart"></ul>

@section scripts{
    <script src="https://d3js.org/d3.v5.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $.ajax('Purchases/DatesStatistics/').done(function (grouped_purchases) {
                var svg = d3.select("svg"),
                    margin = 200,
                    width = svg.attr("width") - margin,
                    height = svg.attr("height") - margin

                svg.append("text")
                    .attr("transform", "translate(100,0)")
                    .attr("x", 50)
                    .attr("y", 50)
                    .attr("font-size", "24px")
                    .text("Revenue By Date Statistics")

                var xScale = d3.scaleBand().range([0, width]).padding(0.4),
                    yScale = d3.scaleLinear().range([height, 0]);

                var g = svg.append("g")
                    .attr("transform", "translate(" + 100 + "," + 100 + ")");

                xScale.domain(grouped_purchases.map(function (d) {
                    return d.orderDate.substring(0, 10);
                }));
                yScale.domain([0, d3.max(grouped_purchases, function (d) {
                    return d.revenue;
                })]);

                g.append("g")
                    .attr("transform", "translate(0," + height + ")")
                    .call(d3.axisBottom(xScale))
                    .append("text")
                    .attr("y", height - 250)
                    .attr("x", width - 100)
                    .attr("text-anchor", "end")
                    .attr("stroke", "black")
                    .text("Date");

                g.append("g")
                    .call(d3.axisLeft(yScale).tickFormat(function (d) {
                        return "$" + d;
                    })
                        .ticks(10))
                    .append("text")
                    .attr("transform", "rotate(-90)")
                    .attr("y", 6)
                    .attr("dy", "-5.1em")
                    .attr("text-anchor", "end")
                    .attr("stroke", "black")
                    .text("Total Revenue");

                g.selectAll(".bar")
                    .data(grouped_purchases)
                    .enter().append("rect")

                    .style("fill", "steelblue")
                    .attr("class", "bar")
                    .attr("x", function (d) {
                        return xScale(d.orderDate.substring(0, 10));
                    })
                    .attr("y", function (d) {
                        return yScale(d.revenue);
                    })
                    .attr("width", xScale.bandwidth())
                    .attr("height", function (d) {
                        return height - yScale(d.revenue);
                    });
            });
        });

        $(function () {

            $.get('Purchases/GenersStatistics/').done(function (grouped_purchases) {
                var width = 450
                height = 450
                margin = 40;

                // The radius of the pieplot is half the width or half the height (smallest one)
                var radius = Math.min(width, height) / 2 - margin;

                // append the svg object to the div
                var svg = d3.select("#postsChart")
                    .append("svg")
                    .attr("width", width)
                    .attr("height", height)
                    .append("g")
                    .attr("transform", "translate(" + width / 2 + "," + height / 2 + ")");

                var sumAllCount = 0;

                // Create data
                var data = grouped_purchases.map(function (d) {
                    sumAllCount += d.count;
                    return { key: d.genre, value: d.count };
                })

                // set the color scale
                var color = d3.scaleOrdinal()
                    .domain(data)
                    .range(d3.schemeSet2);

                // Compute the position of each group on the pie
                var pie = d3.pie()
                    .value(function (d) {
                        return d.value;
                    });

                var data_ready = pie(data);
                // Now I know that group A goes from 0 degrees to x degrees and so on

                // shape helper to build arcs
                var arcGenerator = d3.arc()
                    .innerRadius(0)
                    .outerRadius(radius);

                // Build the pie chart
                svg.selectAll('mySlices')
                    .data(data_ready)
                    .enter()
                    .append('path')
                    .attr('d', arcGenerator)
                    .attr('fill', function (d) {
                        return (color(d.data.key))
                    })
                    .attr("stroke", "black")
                    .style("stroke-width", "2px")
                    .style("opacity", 0.7);

                // annotation
                svg.selectAll('mySlices')
                    .data(data_ready)
                    .enter()
                    .append('text')
                    .text(function (d) {
                        return d.data.key + " " + Math.round((d.data.value * 100) / sumAllCount) + "%";
                    })
                    .attr("transform", function (d) {
                        return "translate(" + arcGenerator.centroid(d) + ")";
                    })
                    .style("text-anchor", "middle")
                    .style("font-size", 17);
            });
        });
    </script>
}

Bookstore/Views/Purchases/Receipt.cshtml
@model Bookstore.Models.PurchaseReceiptModel

@{
    ViewData["Title"] = "Receipt";
}

<h2>Receipt</h2>

<div>
    <h4>Purchase</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.RecentPurchase.Buyer.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecentPurchase.Buyer.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RecentPurchase.Book.Title)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecentPurchase.Book.Title)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.RecentPurchase.Book.Price)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.RecentPurchase.Book.Price)
        </dd>
    </dl>
    <hr />
    <hr />
    @if (Model.BoookReccomendations.Count > 0)
    {
        <h2>Recommendations</h2>
        <hr />
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="center-block">
                        @foreach (var recommendation in Model.BoookReccomendations)
                        {
                            <div class="col-lg-3">
                                <h3>
                                    @Html.DisplayFor(modelItem => recommendation.Item1)
                                </h3>
                                <b>
                                    @Html.DisplayNameFor(modelItem => recommendation.Item2.Title)
                                </b>
                                <p>
                                    @Html.DisplayFor(modelItem => recommendation.Item2.Title)
                                </p>
                                <b>
                                    @Html.DisplayNameFor(modelItem => recommendation.Item2.Author)
                                </b>
                                <p>
                                    @Html.DisplayFor(modelItem => recommendation.Item2.Author)
                                </p>
                                <b>
                                    @Html.DisplayNameFor(modelItem => recommendation.Item2.Rating)
                                </b>
                                <p>
                                    @Html.DisplayFor(modelItem => recommendation.Item2.Rating)
                                </p>
                                <b>
                                    @Html.DisplayNameFor(modelItem => recommendation.Item2.Price)
                                </b>
                                <p>
                                    @Html.DisplayFor(modelItem => recommendation.Item2.Price)
                                </p>
                                <a asp-action="Buy" asp-route-BuyerPhone="@Model.RecentPurchase.Buyer.Phone" asp-route-BookId="@recommendation.Item2.Id">Buy This Book!</a>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <hr />
        <hr />
    }
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }